<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPINHYDW0993" name="com.epam.calculatorTests.CalculatorTests" tests="30" failures="6" timestamp="01 Jun 2017 16:53:24 GMT" time="0.034" errors="0">
  <testcase name="tangentOfDouble" time="0.002" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="powerOfDouble" time="0.002" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="sumOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="divisionOfLong" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="powerOfDouble" time="0.000" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="cosineOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="squarerootOfDouble" time="0.000" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="cotangetOfdouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [3.82054149728] but found [0.25055040799817446]">
      <![CDATA[java.lang.AssertionError: expected [3.82054149728] but found [0.25055040799817446]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.epam.calculatorTests.CalculatorTests.cotangetOfdouble(CalculatorTests.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- cotangetOfdouble -->
  <testcase name="isPositiveNumber" time="0.002" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="sumOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="powerOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="squarerootOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="isPositiveNumber" time="0.000" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="multiplicationOfDouble" time="0.000" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [829.98796244] but found [829.0]">
      <![CDATA[java.lang.AssertionError: expected [829.98796244] but found [829.0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.epam.calculatorTests.CalculatorTests.multiplicationOfDouble(CalculatorTests.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- multiplicationOfDouble -->
  <testcase name="cosineOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="differenceOfDouble" time="0.002" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="tangentOfDouble" time="0.000" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="differenceOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="multiplicationOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [1741642.8496062] but found [1741642.0]">
      <![CDATA[java.lang.AssertionError: expected [1741642.8496062] but found [1741642.0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.epam.calculatorTests.CalculatorTests.multiplicationOfDouble(CalculatorTests.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- multiplicationOfDouble -->
  <testcase name="cosineOfDouble" time="0.005" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="tangentOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="divisionOfLong" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="isPositiveNumber" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="cotangetOfdouble" time="0.002" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [0.64209261593] but found [0.7615941559557649]">
      <![CDATA[java.lang.AssertionError: expected [0.64209261593] but found [0.7615941559557649]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.epam.calculatorTests.CalculatorTests.cotangetOfdouble(CalculatorTests.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- cotangetOfdouble -->
  <testcase name="cotangetOfdouble" time="0.000" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [1.07342614855] but found [0.6351489523872873]">
      <![CDATA[java.lang.AssertionError: expected [1.07342614855] but found [0.6351489523872873]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.epam.calculatorTests.CalculatorTests.cotangetOfdouble(CalculatorTests.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- cotangetOfdouble -->
  <testcase name="differenceOfDouble" time="0.002" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="sumOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="multiplicationOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [8868718.08] but found [8868718.0]">
      <![CDATA[java.lang.AssertionError: expected [8868718.08] but found [8868718.0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.epam.calculatorTests.CalculatorTests.multiplicationOfDouble(CalculatorTests.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- multiplicationOfDouble -->
  <testcase name="divisionOfLong" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="squarerootOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
</testsuite> <!-- com.epam.calculatorTests.CalculatorTests -->
